package com.constructflow.boundary.reports.decorator;

import com.constructflow.boundary.reports.ReportFactory;

/**
 * DECORATOR PATTERN - Concrete Decorator
 * Adds metadata headers to reports (project info, generated info, etc.)
 */
public class MetadataHeaderDecorator extends ReportDecorator {
    private String projectName;
    private String generatedBy;
    
    public MetadataHeaderDecorator(ReportFactory factory, String projectName, String generatedBy) {
        super(factory);
        this.projectName = projectName;
        this.generatedBy = generatedBy;
    }
    
    @Override
    protected void applyDecoration(String reportType) {
        System.out.println("[MetadataHeaderDecorator] Adding metadata header to " + reportType);
        System.out.println("[MetadataHeaderDecorator] Project: " + projectName);
        System.out.println("[MetadataHeaderDecorator] Generated by: " + generatedBy);
    }
    
    public String getProjectName() {
        return projectName;
    }
    
    public String getGeneratedBy() {
        return generatedBy;
    }
}
